require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FileObjectsController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectFile. As you add validations to ProjectFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "order" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all file_objects as @file_objects" do
      file_object = FileObject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:file_objects).should eq([file_object])
    end
  end

  describe "GET show" do
    it "assigns the requested file_object as @file_object" do
      file_object = FileObject.create! valid_attributes
      get :show, {:id => file_object.to_param}, valid_session
      assigns(:file_object).should eq(file_object)
    end
  end

  describe "GET new" do
    it "assigns a new file_object as @file_object" do
      get :new, {}, valid_session
      assigns(:file_object).should be_a_new(FileObject)
    end
  end

  describe "GET edit" do
    it "assigns the requested file_object as @file_object" do
      file_object = FileObject.create! valid_attributes
      get :edit, {:id => file_object.to_param}, valid_session
      assigns(:file_object).should eq(file_object)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FileObject" do
        expect {
          post :create, {:file_object => valid_attributes}, valid_session
        }.to change(FileObject, :count).by(1)
      end

      it "assigns a newly created file_object as @file_object" do
        post :create, {:file_object => valid_attributes}, valid_session
        assigns(:file_object).should be_a(FileObject)
        assigns(:file_object).should be_persisted
      end

      it "redirects to the created file_object" do
        post :create, {:file_object => valid_attributes}, valid_session
        response.should redirect_to(FileObject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved file_object as @file_object" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileObject.any_instance.stub(:save).and_return(false)
        post :create, {:file_object => { "order" => "invalid value" }}, valid_session
        assigns(:file_object).should be_a_new(FileObject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileObject.any_instance.stub(:save).and_return(false)
        post :create, {:file_object => { "order" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested file_object" do
        file_object = FileObject.create! valid_attributes
        # Assuming there are no other project_files in the database, this
        # specifies that the ProjectFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FileObject.any_instance.should_receive(:update).with({ "order" => "" })
        put :update, {:id => file_object.to_param, :file_object => { "order" => "" }}, valid_session
      end

      it "assigns the requested file_object as @file_object" do
        file_object = FileObject.create! valid_attributes
        put :update, {:id => file_object.to_param, :file_object => valid_attributes}, valid_session
        assigns(:file_object).should eq(file_object)
      end

      it "redirects to the file_object" do
        file_object = FileObject.create! valid_attributes
        put :update, {:id => file_object.to_param, :file_object => valid_attributes}, valid_session
        response.should redirect_to(file_object)
      end
    end

    describe "with invalid params" do
      it "assigns the file_object as @file_object" do
        file_object = FileObject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileObject.any_instance.stub(:save).and_return(false)
        put :update, {:id => file_object.to_param, :project_file => { "order" => "invalid value" }}, valid_session
        assigns(:file_object).should eq(file_object)
      end

      it "re-renders the 'edit' template" do
        file_object = FileObject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileObject.any_instance.stub(:save).and_return(false)
        put :update, {:id => file_object.to_param, :file_object => { "order" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested file_object" do
      file_object = FileObject.create! valid_attributes
      expect {
        delete :destroy, {:id => file_object.to_param}, valid_session
      }.to change(FileObject, :count).by(-1)
    end

    it "redirects to the file_object list" do
      file_object = FileObject.create! valid_attributes
      delete :destroy, {:id => file_object.to_param}, valid_session
      response.should redirect_to(file_objects_url)
    end
  end

end
